"""Adapters that run sampler backends from normalized node settings."""

from __future__ import annotations

from .flow_sampler import run_comfy_anima_sampler
from .node_settings import _cfg_domain_from_settings


def _run_sampler_with_params(
    *,
    model,
    positive,
    negative,
    latent_image,
    params: dict,
    denoise,
    add_noise,
    disable_pbar,
    collect_diagnostics=False,
):
    return run_comfy_anima_sampler(
        model=model,
        positive=positive,
        negative=negative,
        latent=latent_image,
        seed=int(params["seed"]),
        steps=int(params["steps"]),
        cfg=float(params["cfg"]),
        denoise=denoise,
        flow_solver=str(params["flow_solver"]),
        flow_er_order=int(params["flow_er_order"]),
        flow_pc3_gamma=float(params["flow_pc3_gamma"]),
        flow_pc3_tolerance=float(params["flow_pc3_tolerance"]),
        flow_unipc_order=int(params["flow_unipc_order"]),
        flow_unipc_solver_type=str(params["flow_unipc_solver_type"]),
        flow_unipc_lower_order_final=bool(params["flow_unipc_lower_order_final"]),
        flow_unipc_disable_corrector_first=int(params["flow_unipc_disable_corrector_first"]),
        flow_unipc_thresholding=bool(params["flow_unipc_thresholding"]),
        flow_unipc_dynamic_thresholding_ratio=float(params["flow_unipc_dynamic_thresholding_ratio"]),
        flow_unipc_sample_max_value=float(params["flow_unipc_sample_max_value"]),
        flow_schedule=str(params["flow_schedule"]),
        flow_shift=float(params["flow_shift"]),
        flow_rho7_tail_auto=bool(params["flow_rho7_tail_auto"]),
        final_clean_pass=bool(params["final_clean_pass"]),
        cosmos_sigma_max=float(params["cosmos_sigma_max"]),
        cosmos_sigma_min=float(params["cosmos_sigma_min"]),
        denoise_legacy_progress=bool(params["denoise_legacy_progress"]),
        cfg_schedule_domain=_cfg_domain_from_settings(params),
        cfg_schedule_mode=str(params["cfg_schedule_mode"]),
        early_cfg_boost=float(params["early_cfg_boost"]),
        early_cfg_until=float(params["early_cfg_until"]),
        late_cfg_scale=float(params["late_cfg_scale"]),
        late_cfg_start=float(params["late_cfg_start"]),
        cfg_early_scale=float(params["cfg_early_scale"]),
        cfg_early_ramp_end=float(params["cfg_early_ramp_end"]),
        cfg_peak_boost=float(params["cfg_peak_boost"]),
        cfg_bump_start=float(params["cfg_bump_start"]),
        cfg_bump_end=float(params["cfg_bump_end"]),
        cfg_beta_alpha=float(params["cfg_beta_alpha"]),
        cfg_beta_beta=float(params["cfg_beta_beta"]),
        cfg_interval_start=float(params["cfg_interval_start"]),
        cfg_interval_rise_end=float(params["cfg_interval_rise_end"]),
        cfg_interval_fall_start=float(params["cfg_interval_fall_start"]),
        cfg_interval_end=float(params["cfg_interval_end"]),
        rf_endpoint_noise_refresh_enabled=bool(params["rf_endpoint_noise_refresh_enabled"]),
        rf_endpoint_noise_refresh_strength=float(params["rf_endpoint_noise_refresh_strength"]),
        rf_endpoint_noise_refresh_until=float(params["rf_endpoint_noise_refresh_until"]),
        add_noise=add_noise,
        disable_pbar=disable_pbar,
        collect_diagnostics=collect_diagnostics,
    )
